project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: about.html
        text: About
      - text: Hands-on Exercises
        menu:
          - href: L1/handson_ex01.html
            text: Hands-on Exercise 1
          - href: L2/handson_ex02.html
            text: Hands-on Exercise 2
          - href: L3/handson_ex03.html
            text: Hands-on Exercise 3
          - href: L4/handson_ex04.html
            text: Hands-on Exercise 4
          - href: L5/handson_ex05.html
            text: Hands-on Exercise 5
          - href: L6/handson_ex06.html
            text: Hands-on Exercise 6
          - href: L7/handson_ex07.html
            text: Hands-on Exercise 7
          - href: L8/handson_ex08.html
            text: Hands-on Exercise 8
          - href: L9/handson_ex09.html
            text: Hands-on Exercise 9
          - href: L10/handson_ex10.html
            text: Hands-on Exercise 10
      - text: In-class Exercises
        menu:
          - href: https://public.tableau.com/app/profile/jia.yi.lau/viz/In-ClassEx2/SuperStoreSalesandProfitReport
            text: In-class Exercise 2
          - href: https://public.tableau.com/app/profile/jia.yi.lau/viz/In-Class_Ex03_17462578872460/SalesversusProfitDB
            text: In-class Exercise 3
          - href: https://public.tableau.com/app/profile/jia.yi.lau/viz/In-classEx06_17480706149670/VisitorarrivalsbyCountry
            text: In-class Exercise 6
          - href: https://public.tableau.com/app/profile/jia.yi.lau/viz/InClassEx08/SGPools
            text: In-class Exercise 8A
          - href: https://public.tableau.com/app/profile/jia.yi.lau/viz/InClassEx08b/SingaporePropertyPrice
            text: In-class Exercise 8B
          - href: https://public.tableau.com/app/profile/jia.yi.lau/viz/InClassEx09_17504906854160/SingaporePopulation
            text: In-class Exercise 9A
          - href: Ahttps://public.tableau.com/app/profile/jia.yi.lau/viz/In-ClassEx09C-PropertyWise/BePropertyWiseorOtherwise   
            text: In-class Exercise 9C
          - href: https://public.tableau.com/app/profile/jia.yi.lau/viz/In-ClassEx10_17510911920130/Dashboard1
            text: In-class Exercise 10A
          - href: L10/In-Class_Ex10/In-Class_Ex10-Quarto_Dashboard.html
            text: In-class Exercise 10B
      - text: Take-home Exercises
        menu:
          - href: T1/takehome_ex01.html
            text: Take-home Exercise 1
          - href: T1/takehome_ex01a.html
            text: Take-home Exercise 1A
          - href: T2/takehome_ex02.html
            text: Take-home Exercise 2
          - href: https://isss608-ay2024-25apr-g7.netlify.app/take-home_ex03
            text: Take-home Exercise 3

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

